import { SVGProps } from "react";

export type IconSvgProps = SVGProps<SVGSVGElement> & {
  size?: number;
};

export * from "./asociacion";
export * from "./actividadPlan";
export * from "./baseEntity";
export * from "./centroFormacion";
export * from "./costo";
export * from "./criterioEvaluacion";
export * from "./datoMensual";
export * from "./departamento";
export * from "./diagnosticoPlantilla";
export * from "./enumerators";
export * from "./evaluacionDiagnostico";
export * from "./formacion";
export * from "./inversion";
export * from "./media";
export * from "./modeloNegocio";
export * from "./municipio";
export * from "./pagination";
export * from "./participante";
export * from "./participanteAsociacion";
export * from "./permission";
export * from "./planDeAccion";
export * from "./planMercadeo";
export * from "./portafolio";
export * from "./proyeccionFinanciera";
export * from "./proyectoProductivo";
export * from "./regional";
export * from "./respuestaCriterio";
export * from "./role";
export * from "./seccionDiagnostico";
export * from "./seguimientoActividad";
export * from "./servicioParticipante";
export * from "./strapi";
export * from "./user";
export * from "./vereda";
